name: auto-open-pr
on:
  push:
    branches:
      - actions
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: checkout

    - name: Create pull request
      id: create_pull_request
      uses: actions/create-pull-request@v2
      with:
        title: 'Auto Pull Request'
        head: branch-to-merge
        base: main
        labels: 'auto-merge'
        approve: true

    - name: Merge pull request
      if: steps.create_pull_request.outputs.pull_request_number
      uses: actions/merge-pull-request@v2
      with:
        pull_request_number: ${{ steps.create_pull_request.outputs.pull_request_number }}
        commit-message: 'Auto merge'
