name: Auto approve and merge PRs by dependabot

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot 
    runs-on: ubuntu-latest 
    permissions:
      pull-requests: write
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0 
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          review-message: "Auto approved automated PR"
