name: Auto Pull Request, Approve, and Merge
on:
  push:
    branches: 
      - actions
jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      # Checkout project repository
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Create Pull Request
        id: npm-publish
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: npm publish - open PR - added tag
          title: npm publish - open PR
          body: npm publish - open PR
          base: main
          labels: automated-pr, npm publish
          branch: actions
          delete-branch: true
      # auto approve PR
      - name: Auto approve
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.npm-publish.outputs.pull-request-number }}
      # auto merge PR
      - name: Auto merge PR
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.npm-publish.outputs.pull-request-number }}
          method: squash
