name: Auto Pull Request, Approve, and Merge

on:
  push:
    branches:
      - murali

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create pull request
      id: create_pull_request
      uses: actions/create-pull-request@v2
      with:
        title: 'Auto Pull Request'
        head: murali
        base: main
        labels: 'auto-merge'

    - name: Approve pull request
      if: steps.create_pull_request.outputs.pull_request_number
      uses: actions/request-review@v2
      with:
        pull_request_number: ${{ steps.create_pull_request.outputs.pull_request_number }}
        reviewers: bds1959
      
    - name: Merge pull request
      if: steps.create_pull_request.outputs.pull_request_number
      uses: actions/merge-pull-request@v2
      with:
        pull_request_number: ${{ steps.create_pull_request.outputs.pull_request_number }}
        commit-message: 'Auto merge'
